### ISSUE TITLE
Additional Field Level Attributes

### ISSUE THREAD

**Issue by aognenoff** [keirbowden/LDNSCall2020Plugin#11]
This is a fantastic project Keir!  I was wondering if you've considered adding support for additional field level attributes like field usage, data classification, is it encrypted, etc.  I tried to explore where that could be added but I'll be the first to admit plugins are not an area I've dived deep into yet.

**Comment by keirbowden** [comment]
Hey Andy - good to hear from you.

Adding additional attributes on fields does require some coding, but if they are extracted from the CustomField metadata definition, it is pretty simple for me to add. So for the additional attributes you'd like, if you can point me at the field on the [CustomField metadata](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/customfield.htm) in a comment on this issue, I can look at adding them in. 

If the attribute is derived from elsewhere in the metadata (like the page layout usage is, for example) this is a bigger effort and probably require an issue per attribute, so feel free to create more issues with the details.

**Comment by aognenoff** [comment]
I think these would all come from the CustomField metadata:

securityClassification
complianceGroup
businessStatus
encrypted (encryptionScheme) - just the boolean would be fine but having the scheme is a bonus

Thanks!

**Comment by keirbowden** [comment]
Thanks for the info - these are available in the latest version of the plug-in (3.5.1). As this makes the pages quite wide the columns are now configurable - blog post to follow.
