### ISSUE TITLE
Error when running doc command: "Cannot read properties of undefined (reading 'toLowerCase')"

### ISSUE THREAD

**Issue by jimrae** [keirbowden/LDNSCall2020Plugin#14]
Installed the latest version (4.0.2), created a config file based on the sample (only change, updated the Events object group to be the Account object group, with the Account, Contact objects listed.  on running the command:
sfdx bbdoc:doc -r ./report -s force-app/main/default/ -c config/bbdoc-config.json 

from my project home directory, I get a notification "Documenting Org" and then the message:

ERROR running bbdoc:doc:  Cannot read properties of undefined (reading 'toLowerCase')

This is my config file:

`{
    "title": "Instance Overview",
    "subtitle": "From the metadata source",
    "objects": {
        "name": "objects",
        "description": "Custom Objects", 
        "backgroundColor" : "#ff8b00",
        "color": "#ffffff",
        "subdirectory": "objects",
        "reportDirectory": "objs",
        "image": "images/objects.png",
        "suffix":"object",
        "groups": {
            "feeds": {
                "name":"Account", 
                "title":"Account Objects",
                "backgroundColor" : "#c9a9d6",
                "color": "#01010c",
                "columns":["Name", "Label", "Type", "Description", "Info", "Page Layouts", "Security", "Compliance", "Encrypted"],
                "description": "Objects associated with events",
                "objects": "Account, Contact"
            }
            ,
            "other": {
                "name":"other", 
                "columns":["Name", "Label", "Type", "Description", "Info", "Page Layouts", "Security", "Compliance", "In Use", "Encrypted"],
                "title":"Uncategorised Objects",
                "description": "Objects that do not fall into any other category"
            }
        }
    },
    "triggers": {
        "name": "triggers",
        "description": "Triggers providing automation", 
        "image": "images/triggers.png",
        "subdirectory": "triggers",
        "suffix":"trigger",
        "groups": {
            "other": {
                "name":"other", 
                "title":"All Triggers",
                "description": "All triggers defined in the example repo"
            }
        }
    },
    "auraenabled": {
        "name": "auraenabled",
        "description": "AuraEnabled Class Access", 
        "subdirectory": ".",
        "image": "images/auraenabled.png",
        "suffix":"object",
        "groups": {
            "other": {
                "name":"other", 
                "title":"AuraEnabled Components",
                "description": "All components with Apex controllers"
            }
        }
    },
    "flows": {
        "name": "flows",
        "description": "Flows providing automation", 
        "image": "images/flows.jpg",
        "subdirectory": "flows",
        "suffix":"flow",
        "groups": {
            "other": {
                "name":"other", 
                "title":"All Flows",
                "description": "All flows defined in the example repo"
            }
        }
    },
    "orderofexecution": {
        "name": "orderofexecution",
        "description": "Order of Execution", 
        "subdirectory": ".",
        "image": "images/order.png"
    }
}`

**Comment by keirbowden** [comment]
Thanks for the report - I'll take a look.

**Comment by keirbowden** [comment]
Hey Jim,

I _think_ that this is because I'm encountering an issue parsing a trigger. I've kind of reproduced it by making one of my test triggers unparseable and applied some defensive code and improved logging.

I've pushed 4.0.3 - can you update and try again when you have a moment please. If it is related to trigger parsing it will now skip the trigger and output a warning - if you see that we can pick up again in here.

**Comment by jimrae** [comment]
@keirbowden (Bob), I think you are right.  For some reason, my project includes all of the managed package triggers from the org. I think one of my developers was overzealous creating the repo that I cloned the project from.  Anyway, I updated to 4.0.3, and now get a different error:

`sfdx bbdoc:doc -r ./report -s force-app/main/default/ -c config/bbdoc-config.json 
Documenting Org
Warning - unable to parse trigger ChargentOrders__TChargentOrderTrigger
Warning - unable to parse trigger ChargentOrders__TChargentPaymentRequestTrigger
Warning - unable to parse trigger ChargentOrders__TransactionTrigger
Warning - unable to parse trigger ChargentOrders__testAsync
Warning - unable to parse trigger DOZISF__AccountTrigger
Warning - unable to parse trigger DOZISF__ContactTrigger
Warning - unable to parse trigger DOZISF__LeadTrigger
Warning - unable to parse trigger et4ae5__JBIntCDCEventTrigger
Warning - unable to parse trigger et4ae5__assignETPermission
Warning - unable to parse trigger et4ae5__assignSendDefRecordType
Warning - unable to parse trigger et4ae5__assignSmsDefRecordType
Warning - unable to parse trigger et4ae5__cascadeDeleteIERs
Warning - unable to parse trigger et4ae5__cascadeDeleteILDs
Warning - unable to parse trigger et4ae5__createQueueableJobFromJB_Event
Warning - unable to parse trigger et4ae5__createQueueableJobFromJB_Flow_Event
Warning - unable to parse trigger et4ae5__sendDefChange
Warning - unable to parse trigger et4ae5__smsDefChange
Warning - unable to parse trigger et4ae5__trigSendDefChange
Warning - unable to parse trigger et4ae5__updateBURecord
Warning - unable to parse trigger et4ae5__updateCampaignMemberStatusForIER
An error occurred documenting the org - TypeError: Cannot read properties of undefined (reading 'get')
Stack trace:
TypeError: Cannot read properties of undefined (reading 'get')
    at /Users/jimrae/.local/share/sfdx/node_modules/bbdoc/lib/shared/processors/trigger/triggers.js:86:72
    at Array.forEach (<anonymous>)
    at /Users/jimrae/.local/share/sfdx/node_modules/bbdoc/lib/shared/processors/trigger/triggers.js:66:58
    at Array.forEach (<anonymous>)
    at /Users/jimrae/.local/share/sfdx/node_modules/bbdoc/lib/shared/processors/trigger/triggers.js:57:28
    at Array.forEach (<anonymous>)
    at TriggerProcessor.checkDuplicates (/Users/jimrae/.local/share/sfdx/node_modules/bbdoc/lib/shared/processors/trigger/triggers.js:56:29)
    at TriggerProcessor.process (/Users/jimrae/.local/share/sfdx/node_modules/bbdoc/lib/shared/processors/trigger/triggers.js:32:14)
    at Documentor.process (/Users/jimrae/.local/share/sfdx/node_modules/bbdoc/lib/shared/documentor.js:66:33)
    at Documentor.document (/Users/jimrae/.local/share/sfdx/node_modules/bbdoc/lib/shared/documentor.js:39:26)
Documented Org
Report generated at report/index.html`

**Comment by jimrae** [comment]
Also, so you know, the last line of the output says "Report generated at report/index.html" but, there is no index.html in the report folder.

**Comment by keirbowden** [comment]
Thanks for the update - I'll do some digging with packages triggers and add some more defensive code.

**Comment by jimrae** [comment]
Looking forward to seeing it in action, looks like a great utility. Thanks for all of your contributions to the Obama!

**Comment by jimrae** [comment]
@keirbowden one other comment for you. I tried to run the plugin in a completely different project, one that did not have any managed package metadata in it, and I get the same error I posted yesterday, the "TypeError: Cannot read properties o undefined (reading 'get')"

**Comment by keirbowden** [comment]
Hi Jim - thanks for the information. I was able to reproduce the error so I've applied a fix for that. It will also stop telling you it was successful when it wasn't!

I've pushed 4.0.4 if you want to give that a test.

**Comment by jimrae** [comment]
Yes, It worked correctly.
