### ISSUE TITLE
Ability to have a user defined report title

### ISSUE THREAD

**Issue by brightgen-cni** [keirbowden/LDNSCall2020Plugin#7]
Hi,

To begin with, many thanks for putting effort on such a great open source tool.

And now, a small feature request, which I felt while creating scripts for the end users. I could use 'sed' in my bash script to replace the default 'Org Report' title to have a different one. So, new feature will help simplify the automation even further.

If possible, then we need the ability to specify a report title of our own instead of the default title 'Org Report'. Either as a command switch (e.g. -H <my oen report title>) or as part of config file, or whatever way makes more sense.

Many thanks in advance and the Best regards
Firoz Mirza

**Comment by keirbowden** [comment]
This is now available in version 3.4 - use sfdx plugins:update to upgrade and check out the blog post at : http://bobbuzz.me.uk/DocOrgTitle

**Comment by brightgen-cni** [comment]
Thank you so much, Keir.
